/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateEmotionalStateArgs } from "./CreateEmotionalStateArgs";
import { UpdateEmotionalStateArgs } from "./UpdateEmotionalStateArgs";
import { DeleteEmotionalStateArgs } from "./DeleteEmotionalStateArgs";
import { EmotionalStateFindManyArgs } from "./EmotionalStateFindManyArgs";
import { EmotionalStateFindUniqueArgs } from "./EmotionalStateFindUniqueArgs";
import { EmotionalState } from "./EmotionalState";
import { User } from "../../user/base/User";
import { EmotionalStateService } from "../emotionalState.service";

@graphql.Resolver(() => EmotionalState)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class EmotionalStateResolverBase {
  constructor(
    protected readonly service: EmotionalStateService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "EmotionalState",
    action: "read",
    possession: "any",
  })
  async _emotionalStatesMeta(
    @graphql.Args() args: EmotionalStateFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [EmotionalState])
  @nestAccessControl.UseRoles({
    resource: "EmotionalState",
    action: "read",
    possession: "any",
  })
  async emotionalStates(
    @graphql.Args() args: EmotionalStateFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<EmotionalState[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "EmotionalState",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => EmotionalState, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "EmotionalState",
    action: "read",
    possession: "own",
  })
  async emotionalState(
    @graphql.Args() args: EmotionalStateFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<EmotionalState | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "EmotionalState",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => EmotionalState)
  @nestAccessControl.UseRoles({
    resource: "EmotionalState",
    action: "create",
    possession: "any",
  })
  async createEmotionalState(
    @graphql.Args() args: CreateEmotionalStateArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<EmotionalState> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "EmotionalState",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"EmotionalState"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        users: args.data.users
          ? {
              connect: args.data.users,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => EmotionalState)
  @nestAccessControl.UseRoles({
    resource: "EmotionalState",
    action: "update",
    possession: "any",
  })
  async updateEmotionalState(
    @graphql.Args() args: UpdateEmotionalStateArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<EmotionalState | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "EmotionalState",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"EmotionalState"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          users: args.data.users
            ? {
                connect: args.data.users,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => EmotionalState)
  @nestAccessControl.UseRoles({
    resource: "EmotionalState",
    action: "delete",
    possession: "any",
  })
  async deleteEmotionalState(
    @graphql.Args() args: DeleteEmotionalStateArgs
  ): Promise<EmotionalState | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "EmotionalState",
    action: "read",
    possession: "any",
  })
  async users(
    @graphql.Parent() parent: EmotionalState,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<User | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "User",
    });
    const result = await this.service.getUsers(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
