/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ConditionListRelationFilter } from "../../condition/base/ConditionListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { DoctorListRelationFilter } from "../../doctor/base/DoctorListRelationFilter";
import { EmotionalStateListRelationFilter } from "../../emotionalState/base/EmotionalStateListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { StringFilter } from "../../util/StringFilter";
@InputType()
class UserWhereInput {
  @ApiProperty({
    required: false,
    type: () => ConditionListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ConditionListRelationFilter)
  @IsOptional()
  @Field(() => ConditionListRelationFilter, {
    nullable: true,
  })
  condition?: ConditionListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => DoctorListRelationFilter,
  })
  @ValidateNested()
  @Type(() => DoctorListRelationFilter)
  @IsOptional()
  @Field(() => DoctorListRelationFilter, {
    nullable: true,
  })
  doctor?: DoctorListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => DoctorListRelationFilter,
  })
  @ValidateNested()
  @Type(() => DoctorListRelationFilter)
  @IsOptional()
  @Field(() => DoctorListRelationFilter, {
    nullable: true,
  })
  doctor_Id?: DoctorListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => EmotionalStateListRelationFilter,
  })
  @ValidateNested()
  @Type(() => EmotionalStateListRelationFilter)
  @IsOptional()
  @Field(() => EmotionalStateListRelationFilter, {
    nullable: true,
  })
  emotionalState?: EmotionalStateListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  firstName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  lastName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  username?: StringFilter;
}
export { UserWhereInput };
